name: jc_module
description: "A new Flutter package project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  auto_route: ^9.2.2
  awesome_dio_interceptor: ^1.2.0
  calendar_date_picker2: ^1.1.7
  dio: ^5.6.0
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  flutter_expanded_tile: ^0.4.0
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.3
  get_it: ^7.7.0
  honeywell_scanner: ^5.0.0+2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  open_file: ^3.5.3
  pdf: ^3.11.1
  qr_code_scanner: ^1.0.1
  riverpod_annotation: ^2.3.5
  url_launcher: ^6.3.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11
  envied_generator: ^0.5.4+1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  riverpod_lint: ^2.3.10
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/svg/
    - assets/cashless/
    - assets/furious/
    - assets/poppins/

  fonts:
    - family: Furious
      fonts:
        - asset: assets/furious/Furious-style.ttf

    - family: Poppins
      fonts:
        - asset: assets/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/poppins/Poppins-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/poppins/Poppins-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/poppins/Poppins-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/poppins/Poppins-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/poppins/Poppins-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/poppins/Poppins-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/poppins/Poppins-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/poppins/Poppins-BlackItalic.ttf
          style: italic
          weight: 900
